# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GysEUr08Jx4AidG-dn-OdqIhMWIk7tTH
"""

import pandas as pd

df = pd.read_csv("sample.csv")
df = df[['text']]  # keep only text column
df.dropna(inplace=True)

df.head()
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

vectorizer = TfidfVectorizer(stop_words='english')
text_vectors = vectorizer.fit_transform(df['text'])
def chatbot_response(user_input):
    user_vector = vectorizer.transform([user_input])
    similarity_scores = cosine_similarity(user_vector, text_vectors)

    best_match_index = np.argmax(similarity_scores)
    best_score = similarity_scores[0][best_match_index]

    if best_score < 0.25:
        return "Sorry, I couldn’t understand your query. Please try again."

    return df.iloc[best_match_index]['text']
import ipywidgets as widgets
from IPython.display import display

input_box = widgets.Text(
    placeholder='Ask a customer support question...',
    description='User:',
    layout=widgets.Layout(width='70%')
)

output_box = widgets.Output()

def on_submit(change):
    output_box.clear_output()
    user_text = change['new']
    if user_text.strip():
        response = chatbot_response(user_text)
        with output_box:
            print("Bot:", response)

input_box.observe(on_submit, names='value')

display(input_box, output_box)